const Database = require('better-sqlite3');
const path = require('path');
const db = new Database(path.join(__dirname, 'server', 'archive.db'));

const newRecords = [
  { id: "rec-book-006", title: "What Congress and Gandhi Have Done to the Untouchables", type: "book", date: "1945-01-01", creator: "Dr. B.R. Ambedkar", language: "English", description: "A comprehensive political critique of Congress and Gandhi's approach to untouchability.", content: "The Untouchables have no reason to be grateful to Gandhi. The Harijan campaign was launched to make Hindus feel they were doing something for Untouchables without making any sacrifice. Gandhi died for the Hindus, not for the untouchables.", source: "Thacker & Co. Ltd., Mumbai", sourceUrl: "", tags: "Gandhi, Congress, Harijan, political critique, untouchability, Poona Pact", provenance: "1st edition 1945, Thacker & Co. Ltd., Bombay." },
  { id: "rec-book-007", title: "Pakistan or the Partition of India", type: "book", date: "1940-01-01", creator: "Dr. B.R. Ambedkar", language: "English", description: "Rigorous political analysis of the Muslim League demand for Pakistan.", content: "The Muslim League demand for Pakistan is not a new demand. It is only a new way of presenting an old demand. The demand is really for separation and not merely partition. Can the Hindus and Muslims live under one constitution?", source: "Thacker & Co. Ltd., Mumbai", sourceUrl: "", tags: "Pakistan, partition, Muslim League, Jinnah, political analysis, communal", provenance: "Published 1940, 2nd edition 1945." },
  { id: "rec-book-008", title: "Riddles in Hinduism", type: "book", date: "1987-01-01", creator: "Dr. B.R. Ambedkar", language: "English", description: "Posthumously published examination of inconsistencies in Hindu religious texts.", content: "The Hindus are taught that the Vedas are eternal and infallible. But the Vedas are not one book but many books written by many authors at different times. How can they be eternal? The Riddle of Hinduism is that it has survived contradictions without resolving them.", source: "Education Department, Government of Maharashtra", sourceUrl: "", tags: "Hinduism, Vedas, religion critique, theology, Puranas", provenance: "Posthumously published as Dr. Babasaheb Ambedkar: Writings and Speeches, Vol. 4, 1987." },
  { id: "rec-book-009", title: "Waiting for a Visa", type: "manuscript", date: "1935-01-01", creator: "Dr. B.R. Ambedkar", language: "English", description: "Autobiographical account of caste-based discrimination experienced by Ambedkar.", content: "I was born an Untouchable. I am an Untouchable. My father was a Subedar in the Indian Army and still I was made to sit on a gunny bag outside the classroom. I remember riding in a bullock cart. The owner refused to drive when he discovered we were Mahars.", source: "Columbia University Libraries", sourceUrl: "https://www.columbia.edu/itc/mealac/pritchett/00ambedkar/txt_ambedkar_waiting.html", tags: "autobiography, untouchability, discrimination, personal account, caste discrimination", provenance: "Handwritten manuscript c. 1935. Published posthumously." },
  { id: "rec-event-011", title: "Founding of Bahishkrit Hitakarini Sabha", type: "event", date: "1924-07-20", creator: "Dr. B.R. Ambedkar", language: "Marathi & English", description: "Organization founded by Ambedkar to promote education and socio-economic improvement among depressed classes.", content: "The Bahishkrit Hitakarini Sabha was founded with the motto: Educate, Agitate, Organize. The Sabha established hostels, libraries and reading rooms for the depressed classes across Maharashtra. It published the journal Bahishkrit Bharat.", source: "Maharashtra State Archives", sourceUrl: "", tags: "Bahishkrit Hitakarini Sabha, education, organization, social reform, Maharashtra", provenance: "Maharashtra State Archives founding records, July 1924." },
  { id: "rec-event-012", title: "Founding of Republican Party of India", type: "event", date: "1956-10-03", creator: "Dr. B.R. Ambedkar", language: "Hindi & Marathi", description: "Dr. Ambedkar announced the founding of the Republican Party of India just eleven days before his conversion to Buddhism.", content: "The Republican Party of India is founded on the principles of liberty, equality and fraternity as enshrined in the Constitution of India. It will work for the political and economic emancipation of all oppressed people regardless of caste or religion. It will fight for the implementation of the Constitutional provisions on reservations and fundamental rights.", source: "Press Trust of India / Janata newspaper", sourceUrl: "", tags: "Republican Party, political party, founding, constitution, reservations", provenance: "Press reports and party founding documents, October 1956." },
  { id: "rec-ms-003", title: "Memorandum to Simon Commission on Behalf of Bahishkrit Hitakarini Sabha", type: "manuscript", date: "1928-05-20", creator: "Dr. B.R. Ambedkar", language: "English", description: "Detailed memorandum demanding constitutional safeguards including reserved seats in legislatures, compulsory education and separate civil service examination.", content: "The Depressed Classes have no political protection whatever. In the Legislative Councils, there is no member to speak for them. They need separate representation. We demand: That the Depressed Classes shall be recognized as a separate element in the population of India. That there shall be reservation of seats in all Legislatures proportionate to their population.", source: "Simon Commission Records, Indian Office Library, London", sourceUrl: "", tags: "Simon Commission, Bahishkrit Hitakarini Sabha, political rights, reserved seats, constitutional safeguards", provenance: "Indian Office Records, British Library, London. Memorandum submitted May 1928." },
  { id: "rec-speech-006", title: "Address at Poona Mahad Conference — Burning of the Manusmriti", type: "speech", date: "1927-12-25", creator: "Dr. B.R. Ambedkar", language: "Marathi", description: "At the second Mahad Conference on Christmas Day 1927, Ambedkar publicly burned a copy of the Manusmriti, the ancient text that codified caste discrimination.", content: "Today we are burning the Manusmriti—not because it is a holy book but because it is a book of slavery. It is a book that denies the humanity of the untouchable. It sanctions the most inhuman treatment of a human being by another human being merely on account of the accident of birth. The burning of Manusmriti is not an act of disrespect toward the Hindus. It is an assertion that we will no longer accept the laws that enslaved us.", source: "Bahishkrit Bharat / Bombay Chronicle", sourceUrl: "", tags: "Manusmriti burning, Mahad Conference, social reform, caste laws, civil rights", provenance: "Contemporary press reports, December 1927." },
  { id: "rec-speech-007", title: "Poona Pact Declaration under Pressure at Yerwada Jail", type: "speech", date: "1932-09-24", creator: "Dr. B.R. Ambedkar", language: "English", description: "Statement made by Dr. Ambedkar after signing the Poona Pact under the pressure of Gandhi's fast-unto-death.", content: "I have signed the agreement. I have done so to save the life of Mr. Gandhi and to prevent the riots and reprisals against the Scheduled Castes that would certainly follow his death. I am not happy with this agreement. Separate electorates would have given us true independence. The increased reserved seats are a pale substitute. But I cannot allow my people to be massacred for a principle, however just. History will judge who was right.", source: "Bombay Chronicle / Times of India", sourceUrl: "", tags: "Poona Pact, Gandhi, fast, separate electorates, reserved seats, Yerwada Jail", provenance: "Press records, September 1932." },
  { id: "rec-debate-007", title: "Debate on the Preamble — Liberty, Equality and Fraternity as the Creed of the Republic", type: "debate", date: "1949-01-17", creator: "Dr. B.R. Ambedkar", language: "English", description: "Constituent Assembly debate on the adoption of the Preamble. Ambedkar explained the meaning of each word and insisted that the Preamble's three values—Liberty, Equality, Fraternity—were borrowed not from the French Revolution but from the teachings of the Buddha.", content: "I have great pleasure in stating that the principles embodied in the Preamble are not borrowed from the French Revolution. They were derived from my teacher, the Lord Buddha, who propounded them as the three pillars of Dhamma: Karuna (compassion, which is fraternity), Prajna (wisdom and equality), and Samata (liberty of the individual). Liberty, Equality and Fraternity—this is the creed of the Indian Republic. Without fraternity, liberty and equality would be no better than a coat of paint.", source: "Constituent Assembly Debates Vol. X", sourceUrl: "https://www.constitutionofindia.net/", tags: "Preamble, liberty, equality, fraternity, Buddha, Dhamma, Republic", provenance: "Official verbatim Parliamentary record." }
];

const insert = db.prepare(`INSERT OR IGNORE INTO archive_records (id, title, type, date, creator, language, description, content, source, sourceUrl, tags, provenance) VALUES (@id, @title, @type, @date, @creator, @language, @description, @content, @source, @sourceUrl, @tags, @provenance)`);
const insertFts = db.prepare(`INSERT OR IGNORE INTO archive_fts (id, title, content, description, creator, tags) VALUES (@id, @title, @content, @description, @creator, @tags)`);

const insertMany = db.transaction((records) => {
  for (const r of records) {
    const res = insert.run(r);
    if (res.changes > 0) insertFts.run(r);
  }
});

insertMany(newRecords);
console.log('DB seeded with', newRecords.length, 'new records!');
